#ifndef FBOOTSTRAPVAR_H
#define FBOOTSTRAPVAR_H

#include <RcppArmadillo.h>
#include "fVAR.h"  // Include to access VARResult struct

// Struct to hold bootstrap VAR results
struct BootstrapVARResult {
  arma::mat ynext;      // T x N bootstrapped data matrix
  arma::vec rademacher; // T_eff-length vector of Rademacher signs
};

// Internal C++ function (for use in other C++ code)
// Accepts VARResult struct directly for efficient C++ to C++ calls
BootstrapVARResult fBootstrapVAR_cpp(const arma::mat& y,
                                     const VARResult& var_result,
                                     const std::string& bootscheme);

// Overload with exogenous regressors: exog_ptr points to the full T x M
// matrix (same one passed to fVAR). Pass nullptr when there are no exog.
BootstrapVARResult fBootstrapVAR_cpp(const arma::mat& y,
                                     const VARResult& var_result,
                                     const std::string& bootscheme,
                                     const arma::mat* exog_ptr);

// Residual-bootstrap overload with indices generated by the caller. This is
// the thread-safe path for OpenMP loops: all RNG work happens beforehand on
// the R main thread, and each worker consumes one fixed index vector.
BootstrapVARResult fBootstrapVAR_cpp(const arma::mat& y,
                                     const VARResult& var_result,
                                     const arma::uvec& residual_indices,
                                     const arma::mat* exog_ptr);

// R wrapper function (for calling from R)
Rcpp::List fBootstrapVAR(const arma::mat& y, 
                         const Rcpp::List& fVAR_result, 
                         const std::string& bootscheme);

#endif
